import { ToolLoopAgent } from 'ai';
import { workspaceTools } from './tools';
import { getGroqModel } from './groqProvider';

console.log('[ReviewerAgent] Reviewer Agent module loaded');

let reviewerAgentInstance: any = null;

export function createReviewerAgent() {
  if (!reviewerAgentInstance) {
    console.log('[ReviewerAgent] Creating Reviewer Agent instance');
    reviewerAgentInstance = new ToolLoopAgent({
      model: getGroqModel('openai/gpt-oss-20b'),
      instructions: 'You are the code review agent for Surfer AI, a coding assistant inside a VS Code extension. Your job is to review code generated by the code agent and provide feedback and format or fix the codeif required. You should only review code when the orchestrator agent sends you code to review. Always send your review back to the orchestrator agent, do not send it directly to the code agent.',
      tools: {
        read_file: workspaceTools.read_file,
      },
    });
    console.log('[ReviewerAgent] Reviewer Agent instance created');
  }
  return reviewerAgentInstance;
}

export const ReviewerAgent = {
  generate: (input: any) => {
    return createReviewerAgent().generate(input);
  }
};
